# Copyright 2022-2023 The VNET Project Authors. All Rights Reserved.

# SPDX-License-Identifier: MIT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesync-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: filesync-controller
  template:
    metadata:
      labels:
        name: filesync-controller
    spec:
      serviceAccountName: filesync-controller
      nodeSelector:
        kubernetes.io/hostname: board-27
      containers:
      - name: fsc
        image: idx/filesync-controller:0.4.0
        imagePullPolicy: IfNotPresent